/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsconfig = {
  aws_project_region: process.env.NEXT_AWS_PROJECT_REGION,
  aws_cognito_identity_pool_id: process.env.NEXT_AWS_COGNITO_IDENTITY_POOL_ID,
  aws_cognito_region: process.env.NEXT_AWS_COGNITO_REGION,
  aws_user_pools_id: process.env.NEXT_AWS_USER_POOLS_ID,
  aws_user_pools_web_client_id: process.env.NEXT_AWS_USER_POOLS_WEB_CLIENT_ID,
  oauth: {},
  aws_cognito_username_attributes: [
    `${process.env.NEXT_AWS_COGNITO_USERNAME_ATTRIBUTES}`,
  ],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: [
    `${process.env.NEXT_AWS_COGNITO_SIGNUP_ATTRIBUTES}`,
  ],
  aws_cognito_mfa_configuration: `${process.env.NEXT_AWS_COGNITO_MFA_CONFIGURATION}`,
  aws_cognito_mfa_types: [`${process.env.NEXT_AWS_COGNITO_MFA_TYPES}`],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: `${process.env.NEXT_PASSWORDPOLICYMINLENGTH}`,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: [
    `${process.env.NEXT_AWS_COGNITO_VERIFICATION_MECHANISMS}`,
  ],
  aws_appsync_graphqlEndpoint: `${process.env.NEXT_AWS_APPSYNC_GRAPHQLENDPOINT}`,
  aws_appsync_region: `${process.env.NEXT_AWS_APPSYNC_REGION}`,
  aws_appsync_authenticationType: `${process.env.NEXT_AWS_APPSYNC_AUTHENTICATIONTYPE}`,
  aws_appsync_apiKey: `${process.env.NEXT_AWS_APPSYNC_APIKEY}`,
};

export default awsconfig;
